### ISSUE TITLE
Error in event filter on 2024.4.0b1

### ISSUE THREAD

**Issue by pdobrien3** [raman325/lock_code_manager#120]
### What happened?

Logger: homeassistant.core
Source: core.py:1434
First occurred: 6:14:32 AM (9 occurrences)
Last logged: 6:58:24 AM

Error in event filter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1434, in _async_fire
    if event_data is None or not event_filter(event_data):
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lock_code_manager/providers/zwave_js.py", line 91, in _zwave_js_event_filter
    evt.data[ATTR_HOME_ID] == self.node.client.driver.controller.home_id
    ^^^^^^^^
AttributeError: 'dict' object has no attribute 'data'

### Steps to reproduce the issue

1.
2.
3.
...

### Home Assistant Version

2024.4.0b1

### What version of Lock Code Manager are you running?

0.4.2

### Lock make and model

Kwikset 916

**Comment by raman325** [comment]
looks like a change in the latest version of HA, thanks for the heads up

**Comment by pdobrien3** [comment]
👍 also be aware that on restarts, the integration needs to be reloaded on my end.  Seems like HAss is starting so quickly these days something gets missed.

**Comment by pdobrien3** [comment]
Logger: homeassistant.core
Source: core.py:1437
First occurred: 1:48:42 PM (66 occurrences)
Last logged: 1:53:19 PM
similar error, different location 
Error in event filter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1437, in _async_fire
    if event_data is None or not event_filter(event_data):
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lock_code_manager/entity.py", line 240, in _event_filter
    any(
  File "/config/custom_components/lock_code_manager/entity.py", line 241, in <genexpr>
    event.data[ATTR_ENTITY_ID] == lock.lock.entity_id for lock in self.locks
    ^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'data'

**Comment by raman325** [comment]
ah damn thanks, forgot about that location

**Comment by pdobrien3** [comment]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1437, in _async_fire
    if event_data is None or not event_filter(event_data):
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lock_code_manager/entity.py", line 242, in _event_filter
    any(data[ATTR_ENTITY_ID] == lock.lock.entity_id for lock in self.locks)
  File "/config/custom_components/lock_code_manager/entity.py", line 242, in <genexpr>
    any(data[ATTR_ENTITY_ID] == lock.lock.entity_id for lock in self.locks)
                                ^^^^^^^^^
AttributeError: 'str' object has no attribute 'lock'
