### ISSUE TITLE
[ISSUE] Not working after install, restart, and setup

### ISSUE THREAD

**Issue by Timeteo** [raman325/lock_code_manager#241]
### What happened?

Followed install and added a lock to the integration along with all of the users and PINs.

- Lock Manager integration shows 1 device with no entities.
- Log states the lock is not connected to Home assistant:
`2024-06-08 11:43:23.940 DEBUG (MainThread) [custom_components.lock_code_manager] b1a7258842d25d3ad69482d020909a4d (Lock Manager): Lock lock.front_door_lock is not connected to Home Assistant yet, waiting 180 seconds before retrying`
- Zwave Integration shows lock as connected: 
![Screenshot 2024-06-08 115304](https://github.com/raman325/lock_code_manager/assets/2643471/7ab1d473-7cd7-4948-8896-63526731672e)
- Dashboard error shows:
`Error loading the view strategy:
TypeError: Cannot read properties of undefined (reading 'entity_id')`

### Steps to reproduce the issue

1. Install via HACS
2. Restart HA
3. Configure lock in Lock Manger Integration
4. Create Lovelace view
5. Viewed dashboard and logs

### Home Assistant Version

2024.6.01

### What version of Lock Code Manager are you running?

0.4.6

### Lock make and model

Schlage BE469

### Relevant log output

```shell
2024-06-08 12:01:53.581 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Side Garage for lock_code_manager
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 809, in async_unload
result = await component.async_unload_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/lock_code_manager/__init__.py", line 264, in async_unload_entry
await async_unload_lock(hass, config_entry)
File "/config/custom_components/lock_code_manager/__init__.py", line 228, in async_unload_lock
if not any(
^^^^
File "/config/custom_components/lock_code_manager/__init__.py", line 229, in <genexpr>
entry != config_entry and lock_entity_id in entry.data[CONF_LOCKS]
~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'locks'
2024-06-08 12:02:28.702 DEBUG (MainThread) [custom_components.lock_code_manager] 4a9bc752564c48579d9eda1671e2e2fd (Front Door): Lock lock.front_door_lock is not connected to Home Assistant yet, waiting 128 seconds before retrying
2024-06-08 12:02:28.702 DEBUG (MainThread) [custom_components.lock_code_manager] 6684a40f2c2e609eb745f48b2061d3d3 (Side Garage): Lock lock.garage_side_door_lock is not connected to Home Assistant yet, waiting 128 seconds before retrying
2024-06-08 12:04:36.702 DEBUG (MainThread) [custom_components.lock_code_manager] 4a9bc752564c48579d9eda1671e2e2fd (Front Door): Lock lock.front_door_lock is not connected to Home Assistant yet, waiting 180 seconds before retrying
2024-06-08 12:04:36.703 DEBUG (MainThread) [custom_components.lock_code_manager] 6684a40f2c2e609eb745f48b2061d3d3 (Side Garage): Lock lock.garage_side_door_lock is not connected to Home Assistant yet, waiting 180 seconds before retrying
2024-06-08 12:05:30.571 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for bootstrap waiting on {<Task pending name='Initial setup for entities for 4a9bc752564c48579d9eda1671e2e2fd' coro=<async_update_listener() running at /config/custom_components/lock_code_manager/__init__.py:418> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[set.remove()]>, <Task pending name='Initial setup for entities for 6684a40f2c2e609eb745f48b2061d3d3' coro=<async_update_listener() running at /config/custom_components/lock_code_manager/__init__.py:418> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[set.remove()]>} - moving forward
```

**Comment by ryanwinter** [comment]
Is this issue resolved, or is it waiting for an upstream fix? I'm still seeing the problem where it appears to be waiting for the lock to become connected, however it is connected:

```
2024-06-17 16:23:46.619 DEBUG (MainThread) [custom_components.lock_code_manager] 616504be0af7bcf4875a7d92fcb67166 (Garage door): Lock lock.garage_inside_door is not connected to Home Assistant yet, waiting 128 seconds before retrying
```
