### ISSUE TITLE
ISSUE: Adding another integration to control a different block of slots causes 

### ISSUE THREAD

**Issue by tykeal** [raman325/lock_code_manager#48]
**Describe the bug**
I added a second integration to control a different set of slots and this causes a 500 error

**Environment (please complete the following information):**

-   OS: HassOS
-   Type of system that HA is running on: KVM
-   Home Assistant version: 2024.2.5
-   Hassio/Docker/Core? HassIO
-   Component version: 0.2.5
-   Lock integration name: ZWave-JS UI
-   Lock make and model: Kwikset 910

**Logs**
``` 2024-03-02 07:48:06.855 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 72, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 223, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 345, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 501, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lock_code_manager/config_flow.py", line 314, in async_step_init
    CONF_LOCKS, default=_get_default(CONF_LOCKS)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lock_code_manager/config_flow.py", line 307, in _get_default
    return user_input.get(key, self.config_entry.data[key])
                               ~~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: 'locks'
```

**Additional context**
I have a use case where I would want to be able to define a LCM that manages 2 locks for a defined set of slots. One lock is shared with multiple blocks and one lock that only shares a single block with the main lock.

For example:

Lock1:
Slots 1 - 5 are not shared with all other locks
Slots 6 - 10 are not shared with any other locks
Slots 11 - 15 are shared with Lock2
Slots 16 - 20 are shared with Lock3

Lock2:
Slots 1 - 5 are shared with Lock1
Slots 6 - 10 are not shared with any other locks
Slots 11 - 15 are shared with Lock1

Lock3:
Slots 1 - 5 are shared with Lock1
Slots 6 - 15 are not shared with any other locks
Slots 16 - 20 are shared with Lock1

The testing that I was specifically doing at this time was to just define a new LCM that was managing a block of slots that are not defined in my first configured LCM

**Reproduction steps**
1. Configure a single LCM with slots 1 - 5 defined against a lock and verify that everything is working
1. Configure a _second_ LCM with slots >5 defined against the _same_ lock as the previous step
1. Observe that new integration shows **No devices or entities** in the configuration page and that if you press the **Configure** button you will error logs similar to the above.

**Comment by raman325** [comment]
> Lock1:
> Slots 1 - 5 are not shared with all other locks

Should this actually be slots 1 - 5 are shared with Lock2 and Lock3?

**Comment by tykeal** [comment]
Yes, a bit of a typo on my part.

Ideally I would like to say this block of slots is shared with all locks known.

This other block of slots is only shared between X number of locks

My specific use case is that I let out several bedrooms in my house via Airbnb. The front door, all bedrooms, and my office all have zwave locks on them.

The first few slots of of each of the locks is presently reserved for manual configuration and I configure my and my wife's door codes into some of those slots.

A block of up to 5 slots is dedicated on the front door and each of the bedrooms that is then controlled via my Rental Control integration (installed twice, once for the front door and once for the bedroom door).

Occasionally I have non-paying guests (that is friends and family) staying with me so I manually configure codes on slots as needed for them.

I would love to be able to have the front door and bedroom door locks all automatically sync without having to have multiple instances of my Rental Control configured. Particularly since it regularly has to access vendor information for calendars. Airbnb doesn't seem to have any major API limits, but a few other vendors that some of my users use do have limits and having to install multiple times can be a bit of a juggling issue for them.

If we could define all the locks at one go and then selectively state which slots should stay in sync between which locks that would be ideal. Even better would be if a slot is a synchronized slot then only the lead lock would have editable entities in the UI.
