### ISSUE TITLE
Manual Setup of custom_componet fails 

### ISSUE THREAD

**Issue by pdobrien3** [raman325/lock_code_manager#54]
**Describe the bug**
I downloaded lock_code_manager.zip, version 0.2.5.  I unzipped the file and added it to a folder named lock_code_manager under my custom_componet folder.  Restart Hass and the setup seemed to go well.  I used the UI method to add locks.  After going through setup, the integration failed.  Here are the logs:

```
2024-03-03 09:07:28.302 ERROR (MainThread) [homeassistant.setup] Error during setup of component lock_code_manager
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 390, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/lock_code_manager/__init__.py", line 73, in async_setup
    for id, data in resources.data.items()
                    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'
```

**Environment (please complete the following information):**

-   OS: Debian VM
-   Type of system that HA is running on: NUC 
-   Home Assistant version: 2024.3.0b5
-   Hassio/Docker/Core: Docker
-   Component version: 0.2.5
-   Lock integration name: zwave_js
-   Lock make and model: Kwikset 916s

**Logs**
Paste your error logs here.

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by raman325** [comment]
hmm that's interesting, can you add a log statement right before a line with the error to log what is in `resources.data`? Looking at the code, it's expected to be a `dict`...

`_LOGGER.error(resources.data)`

**Comment by raman325** [comment]
Sorry before res_id =

**Comment by pdobrien3** [comment]
```
2024-03-03 16:29:56.925 INFO (MainThread) [homeassistant.setup] Setting up lock_code_manager
2024-03-03 16:29:56.926 ERROR (MainThread) [custom_components.lock_code_manager] [{'url': '/local/vertical-stack-in-card.js?v=0.4.4', 'type': 'js'}, {'url': '/local/vacuum-card.js', 'type': 'module'}, {'url': '/local/card-mod.js?v=3.4.2', 'type': 'module'}, {'url': '/local/mini-graph-card-bundle.js?v=0.12.0', 'type': 'module'}, {'url': '/local/button-card.js?v=4.1.2', 'type': 'module'}, {'url': '/local/kiosk-mode.js?v=5.4.0', 'type': 'module'}, {'url': '/local/frigate-card/frigate-hass-card.js', 'type': 'module'}]
2024-03-03 16:29:56.926 ERROR (MainThread) [homeassistant.setup] Error during setup of component lock_code_manager
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 390, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/lock_code_manager/__init__.py", line 74, in async_setup
    for id, data in resources.data.items()
                    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'
```

**Comment by raman325** [comment]
that's interesting... are you by chance using the `extra_module_url` option in your config under `frontend`?

**Comment by raman325** [comment]
Actually, how about `resources` under `lovelace`?

**Comment by raman325** [comment]
I figured out what was happening

**Comment by raman325** [comment]
no worries, this actually exposed a bug so the new implementation should be better!
