### ISSUE TITLE
Integration Fails To Load 

### ISSUE THREAD

**Issue by pdobrien3** [raman325/lock_code_manager#71]
### What happened?

```
2024-03-05 13:50:43.884 INFO (MainThread) [homeassistant.setup] Setting up lock_code_manager
2024-03-05 13:50:43.885 ERROR (MainThread) [homeassistant.setup] Error during setup of component lock_code_manager
Traceback (most recent call last):
  File "/config/custom_components/lock_code_manager/__init__.py", line 88, in async_setup
    res_id = next(
             ^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 390, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/lock_code_manager/__init__.py", line 95, in async_setup
    data = await resources.async_create_item(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ResourceYAMLCollection' object has no attribute 'async_create_item'
```

### Steps to reproduce the issue

1. download, unzip, and place in custom_components/lock_code_manager/
2. Add and configure integration
3. integration errors saying it cannot be setup
...

### Home Assistant Version

2024.3.0b6

### What version of Lock Code Manager are you running?

0.30

### Lock make and model

Kwikset 916 zwave

**Comment by raman325** [comment]
damn, sorry about that, thought these two collection types were the same but clearly not. Easy fix once I get home

**Comment by pdobrien3** [comment]
All good.  Happy to do what i can

**Comment by raman325** [comment]
OK so it looks like you can either use YAML or the UI. When you use YAML, it's read only, so we can't automatically add the resource.

I'll link a PR with a fix as well as instructions for how to make the frontend component available when you are using YAML to define resources

**Comment by pdobrien3** [comment]
I did the UI
